FROM datasetteproject/datasette:latest

RUN datasette install datasette-dashboards
RUN datasette install datasette-chatgpt-plugin
RUN datasette install datasette-simple-html
RUN pip install py-gfm
RUN pip install datasette-render-markdown
RUN datasette install datasette-youtube-embed
RUN datasette install datasette-geojson
RUN pip install datasette-media pyheif
RUN pip install datasette-copyable
RUN datasette install datasette-configure-fts
RUN pip install datasette-search-all
RUN datasette install datasette-nteract-data-explorer
RUN pip install datasette-pretty-json
RUN datasette install datasette-mp3-audio
RUN datasette install datasette-redirect-to-https
RUN datasette install datasette-geojson-map
RUN datasette install datasette-cluster-map
RUN datasette install dogsheep-beta
RUN pip install datasette-vega