global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

groups:
  - name: alerts
    rules:
      # Alert for any instance that has a CPU usage higher than 80% for more than 5 minutes.
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} has high CPU usage"
          description: "{{ $labels.instance }} CPU usage is above 80% for more than 5 minutes."

      # Alert for any instance that has a memory usage higher than 80% for more than 5 minutes.
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} has high memory usage"
          description: "{{ $labels.instance }} memory usage is above 80% for more than 5 minutes."

      # Alert for any instance that has a disk filling up (>80% for >15 minutes).
      - alert: DiskSpaceFillingUp
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} has a disk filling up"
          description: "The disk on {{ $labels.instance }} is filling up (<20% available)."

      # Alert for any instance that is unreachable for more than 5 minutes.
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
