---
- name: Axion server setup
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Update APT repo and cache
      apt:
        update_cache: true
      become: true

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: true
      become: true

    - name: Install specified packages
      apt:
        name:
          - wget
          - gpg
          - coreutils
      become: true

    - name: Install Docker
      block:
        - name: Ensure /etc/apt/keyrings directory exists with correct permissions
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: '0755'

        - name: Download and dearmor the Docker GPG key
          shell:
            cmd: sudo rm -f /etc/apt/keyrings/docker.gpg && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

        - name: Set permissions for docker.gpg
          file:
            path: /etc/apt/keyrings/docker.gpg
            state: file
            mode: '0644'

        - name: Add Docker linux repo
          shell:
            cmd:  echo "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo \"$VERSION_CODENAME\") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        - name: Update APT cache
          apt:
            update_cache: true
          become: true

        - name: Install specified packages
          apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: true
          become: true
          register: output

        - name: Command output
          debug:
            var: output.stdout_lines

    - name: Install Nomad
      block:
        - name: Add Hashicorp GPG key
          shell:
            cmd: sudo rm -f /usr/share/keyrings/hashicorp-archive-keyring.gpg && wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

        - name: Add official Hashicorp linux repo
          shell:
            cmd: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

        - name: Update APT cache
          apt:
            update_cache: true
          become: true

        - name: Install Nomad
          apt:
            name: nomad
            state: present
          become: true
          register: output

        - name: Command output
          debug:
            var: output.stdout_lines

        - name: Command output
          debug:
            var: output.stdout_lines

    - name: Install AWS CLI
      pip:
        name: awscli
        executable: pip3
      register: output

    - name: Command output
      debug:
        var: output.stdout_lines

    - name: Setup Nomad cluster
      block:
        - name: Create nomad config dir
          file:
            path: "{{ nomad_config_dir }}"
            state: directory
            mode: '0755'
          become: true

        - name: Create nomad data dir
          file:
            path: "{{ nomad_data_dir }}"
            state: directory
            mode: '0755'
          become: true

        - name: Copy nomad config file
          copy:
            src: data-files/nomad.hcl
            dest: "{{ nomad_config_dir }}/nomad.hcl"
            owner: axn
            group: axn
            mode: '0644'
          become: true

        - name: Allow traffic on port 4646
          ufw:
            rule: allow
            port: '4646'
            proto: tcp
          become: true

        - name: Start Nomad cluster
          block:
            - name: Enable nomad service
              systemd:
                name: nomad
                enabled: true
              register: output
              become: true

            - name: Command output
              debug:
                var: output.stdout_lines

            - name: Start nomad service
              systemd:
                name: nomad
                state: started
              register: output
              become: true

            - name: Command output
              debug:
                var: output.stdout_lines

            - name: Check nomad service status
              command:
                cmd: systemctl status nomad
              register: service_status
              changed_when: false
              ignore_errors: true
              become: true

            - name: Display nomad service status
              debug:
                var: service_status.stdout_lines
