name: PG_BACKUP Docker Image
run-name: PG_BACKUP Docker Image
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION}}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST}}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD}}
jobs:
  pg_backup:
    name: Create pg_backup docker image
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job is running on ${{ runner.os }}"
      - run: echo "Branch name is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: pg_backup
          platforms: linux/amd64
          file: ./pg_backup/Dockerfile
          push: true
          build-args: |
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}}"
            "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}}"
            "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION}}"
            "POSTGRES_HOST=${{ secrets.POSTGRES_HOST}}"
            "POSTGRES_USER=${{ secrets.POSTGRES_USER}}"
            "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD}}"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pg_backup:0.1
      - run: echo "Job is ${{ job.status }}."
