name: Infra Setup using Terraform
run-name: Create infra
on: workflow_dispatch
env:
  hcloud_token: ${{ secrets.hcloud_token}}
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE}}
jobs:
  terraform:
    name: Run Terraform Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - run: echo "This job is running on a ${{ runner.os }}"
      - run: echo "The name of the branch is ${{ github.ref }} and repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
      - name: Terraform format
        id: fmt
        run: terraform fmt -check
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
